In [1]:
import numpy as np
numbers = np.loadtxt('day6_numbers_example.txt', dtype=int)
operations = np.genfromtxt("day6_operations_example.txt", dtype=str)

In [2]:
numbers

array([[123, 328,  51,  64],
       [ 45,  64, 387,  23],
       [  6,  98, 215, 314]])

In [3]:
operations

array(['*', '+', '*', '+'], dtype='<U1')

In [4]:
def part1(numbers, operations):
    rows, cols = numbers.shape
    runsum = 0
    for j in range(cols):
        col_data = numbers[:, j]
        op = operations[j]
        if op == "+":
            runsum += np.sum(col_data)
        elif op == "*":
            runsum += np.prod(col_data)

    return runsum

part1(numbers, operations)

np.int64(4277556)

In [20]:
# ...existing code...
def get_character_at_index(numpy_string_array, index):
    # removed: not used by new transform_column but kept for compatibility
    def char_extractor(s):
        return s[index] if len(s) > index else ''
    vectorized_extractor = np.vectorize(char_extractor, otypes=[str])
    return vectorized_extractor(numpy_string_array)


def transform_column(col_data):
    str_rows = col_data.astype(str)
    max_len = len(str(max(col_data)))
    transformed = []

    for pos in range(max_len-1, -1, -1):
        num = get_character_at_index(str_rows, pos)
        transformed.append(int(''.join(num)))

    return np.array(transformed)

def part2(numbers, operations):
    rows, cols = numbers.shape
    runsum = 0
    for j in range(cols):
        col_data = transform_column(numbers[:, j])
        print(f"Column {j} transformed -> {col_data}")
        op = operations[j]
        if op == "+":
            runsum += np.sum(col_data)
        elif op == "*":
            runsum += np.prod(col_data)

    return runsum

# Demo: show results for current `numbers` and `operations`
print("part2:", part2(numbers, operations))


Column 0 transformed -> [  3  25 146]
Column 1 transformed -> [  8 248 369]
Column 2 transformed -> [ 75 181 532]
Column 3 transformed -> [  4 431 623]
part2: 7234533


In [19]:
get_character_at_index(numbers[:,3].astype(str), 1)

array(['4', '3', '1'], dtype='<U1')

In [28]:
file_path = 'day6_numbers_example.txt'
with open(file_path, 'r') as f:
    first_line = f.readline()
    num_characters_per_line = len(first_line)-1
    
col_widths = [1] * num_characters_per_line
numbers_chars = np.genfromtxt(
    file_path,
    delimiter=col_widths,
    dtype='U1'
)

In [42]:
numbers

array([[123, 328,  51,  64],
       [ 45,  64, 387,  23],
       [  6,  98, 215, 314]])

In [63]:
def part2(numbers_chars, operations):
    results_df = []
    curr_list = []
    for j in range(num_characters_per_line):
        print(j)
        curr_col = numbers_chars[:,j]
        if np.all(curr_col == ' '):
            results_df.append(np.array(curr_list))
            curr_list = []
            continue
        else:
            curr_list.append(int(''.join(curr_col)))

        if j == num_characters_per_line-1:
            results_df.append(np.array(curr_list))

    return results_df
    transformed_df = np.column_stack(results_df)
    return part1(transformed_df, operations)

In [65]:
file_path = 'day6_numbers_example.txt'
with open(file_path, 'r') as f:
    first_line = f.readline()
    num_characters_per_line = len(first_line)-1
print(num_characters_per_line)
    
col_widths = [1] * num_characters_per_line
numbers_chars = np.genfromtxt(
    file_path,
    delimiter=col_widths,
    dtype='U1'
)
operations = np.genfromtxt("day6_operations_example.txt", dtype=str)
part2(numbers_chars, operations)

15
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


[array([  1,  24, 356]),
 array([369, 248,   8]),
 array([ 32, 581, 175]),
 array([623, 431,   4])]

In [58]:
numbers_chars.shape

(4, 3745)